name: ci
on: [push, pull_request]
jobs:
  run:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk
        architecture: x64
    - name: Run tests
      run: mvn -B package
    - name: trivy
      uses: actions/checkout@v2
    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        security-checks: 'vuln,config,secret'
        hide-progress: false
        format: 'table'
        # Customizing which severities are scanned for is done by adding the following flag: severity: 'UNKNOWN','LOW','MEDIUM','HIGH','CRITICAL'
      env:
        AQUA_KEY: ${{ secrets.AQUA_KEY }}
        AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
        TRIVY_RUN_AS_PLUGIN: 'aqua'
        GITHUB_TOKEN: ${{ github.token }}

